import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import ConvexClientProvider from '@/app/ConvexProviderWithClerk'
import Header from '@/app/header'
import { AuthSideNav } from '@/components/auth-side-nav'
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <Header />
            <div className="flex">
              <AuthSideNav />
              <main className="flex-1 ml-64">
                {children}
              </main>
            </div>
            <Toaster richColors />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}